config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "welcome#index"
  resources :users
  resources :worlds
  #resources :fights
  post "/fights", to: "fights#index"
  post "/chat", to: "chat#index"
  post "/pawn", to: "pawns#index"
  post "/trigger_fight", to: "fights#trigger"
  post "/shop", to: "shop#index"

  get "/test", to: "users#test"
  get "/sign_out", to: "welcome#sign_out"
  get "/setup", to: "welcome#setup"
  post "/messages", to: "welcome#chat"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user

  def sent_at
    created_at.strftime("%m-%d-%Y")
  end

  def timestamp
    created_at.strftime("%R")
  end
end

app/models/pawn.rb
class Pawn < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :pawns

  def avatar_image
    "#{race.downcase}.png"
  end

  class << self
    def races
      ["Pig", "Elephant", "Giraffe", "Monkey"]
    end
  end
end

app/models/world.rb
class World < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ActionController::Cookies
  include Auth
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    @messages = Message.all
  end
end

app/controllers/concerns/auth.rb
module Auth
  extend ActiveSupport::Concern
  included do
    before_action :ensure_logged_in
    helper_method :signed_in?
  end

  class_methods do
    def allow_no_auth(**options)
      skip_before_action :ensure_logged_in, **options
    end
  end

  private
  def ensure_logged_in
    if cookies.encrypted[:user_id]
      Current.user = User.find_by(id: cookies.encrypted[:user_id])
    end
    #else
    #  redirect_to root_url
    #end
  end

  def signed_in?
    Current.user.present?
  end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  def trigger
    FightJob.perform_later(123)
    @thing = 123
  end
end

app/controllers/pawns_controller.rb
class PawnsController < ApplicationController
  def index
    @pawn = Pawn.create(name: "FAKER", user_id: Current.user.id)
  end
end

app/controllers/shop_controller.rb
class ShopController < ApplicationController
  def index
    @items = Item.all
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  allow_no_auth only: [:create]

  def create
    user = User.find_or_create_by(name: params[:name])
    cookies.encrypted[:user_id] = user.id
    redirect_to "/worlds"
  end

  def update
    Current.user.update!(
      race: params[:user][:race],
      first_sign_in: false
    )
    redirect_to "/worlds"
  end

  def test
    ActionCable.server.broadcast("chat", {body: "hell"})
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  allow_no_auth only: [:sign_out]

  def index
    redirect_to "/worlds" if signed_in?
  end

  def sign_out
    cookies.delete :user_id
    Current.user = nil
    redirect_to root_url
  end

  def setup
  end

  def chat
    @message = Message.create!(
      body: params[:message],
      user_id: params[:sender]
    )
    Turbo::StreamsChannel.broadcast_append_to(
      :messages,
      target: "messages",
      partial: "shared/message",
      object: @message
    )
    # forcing a scroll down
    ActionCable.server.broadcast("chat", { body: params[:message], sender: params[:sender] })
  end
end

app/controllers/worlds_controller.rb
class WorldsController < ApplicationController
  def index
    redirect_to "/setup" if Current.user.first_sign_in
    @days = []
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def race_images
    User.races.map { |race| image_url "#{race.downcase}.png" }
  end
end

app/views/chat/index.turbo_stream.erb
<%= turbo_stream.update "action" do %>
  <h3>Chat</h3>
  <div id="chat" data-chat-target="messages">
    <div class="chatContainer">
    <%= turbo_stream_from :messages %>
    <turbo-frame id="messages">
      <%= render partial: "shared/message", collection: @messages %>
    </turbo-frame>
    </div>
  </div>
  <footer>
    <%= form_tag "/messages", remote: true, data: { action: "chat#sendMessage" } do |f| %>
      <%= text_field_tag :message, nil, data: { "chat-target": "input" }, autocomplete: "off", class: "chatMessage" %>
      <%= hidden_field_tag :sender, Current.user.id %>
    <% end %>
  </footer>
<% end %>

app/views/fights/index.turbo_stream.erb
<%= turbo_stream.update "action" do %>
  <div data-controller="fight">
  <%= render(GeneralButton.new(link: "/pawn", text: "Create Pawn")) %>
  <hr>
  <% Current.user.pawns.each do |pawn| %>
    <%= pawn.name %>
  <% end %>
  <hr>
  <%= render(GeneralButton.new(link: "/trigger_fight", text: "Trigger Fight")) %>
  <hr>
  <%= turbo_stream_from :logs %>
    <turbo-frame id="logs">
    <h2>LOGS</h2>
    </turbo-frame>
  </div>
<% end %>

app/views/fights/trigger.turbo_stream.erb
OOOF

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AuctionHouse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= action_cable_meta_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag :all, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="game" id="game">
      <%= render partial: "shared/header" if Current.user.present? %>
    <%= yield %>
    </div>
  </body>
</html>

app/views/pawns/index.turbo_stream.erb
<%= turbo_stream.append "action" do %>
  SOMETHING
  <%= @pawn.id %>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="playerProfile">
    <span class="username"><%= Current.user.name %></span>
  </div>
  <%= link_to image_tag("GUI/icon_setting.png"), sign_out_url, class: "settings" %>
</div>

app/views/shared/_loader.html.erb
LOADING...

app/views/shared/_logs.html.erb
<%= thing %>

app/views/shared/_message.html.erb
<% if @days %>
<% unless @days.include? message.sent_at %>
  <h3><%= message.sent_at %></h3>
  <% @days.append message.sent_at %>
<% end %>
<% end %>
<%= image_tag message.user.avatar_image , class: "avatar" %>
<div class="sent-message">
  <div class="inner-sent-message">
    <span class="user-info">
      <span class="time"><%= message.timestamp %></span>
      <strong><%= message.user.name %></strong>
    </span>
    <br>
    <%= message.body %>
  </div>
</div>

app/views/shared/_race_selector.html.erb
<div>
  <%= image_tag "arrow_left.svg", data: { action: "click->race-selector#moveLeft" } %>
  <%= image_tag "giraffe.png", class: "race-selection", data: { "race-selector-target": "raceImage" } %>
  <strong class="hidden" data-race-selector-target="selection"><%= Current.user.race %></strong>
  <%= image_tag "arrow_right.svg", data: { action: "click->race-selector#moveRight" }, class: "arrow" %>
</div>

app/views/shop/index.turbo_stream.erb
<%= turbo_stream.update "action" do %>
  <div data-controller="shop">
    <div class="shopItems">
    <h2>Shop</h2>
      <% @items.each do |item| %>
        <div class="shopItem" data-action="click->shop#addItem mousemove->shop#mouseover mouseout->shop#mouseout">
          <div class="shopBg">
            <%= image_tag "items/#{item.image}" %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="buyList" data-shop-target="buyList">
      <h2>Buying</h2>
    </div>

    <div class="itemInfo" data-shop-target="itemInfo">
      <h3 data-shop-target="itemName"></h3>
      <p data-shop-target="itemDescription"></p>
      <p data-shop-target="itemPrice"></p>
    </div>
  </div>
<% end %>

app/views/users/test.html.erb
Test page

app/views/welcome/index.html.erb
<div class="center">
  <div class="borderTest">
    <div class="inside">
    <div class="specHeader">Login</div>
      <%= form_with url: "/users", class: "specForm" do |form| %>
        <div class="specInput" data-controller="text-input">
          <%= image_tag "GUI/user-icon.png", class: "input-prompt" %>
          <%= text_field_tag :name, nil, autocomplete: "off", placeholder: "Username", class: "customField", data: { action: "focus->text-input#active blur->text-input#inactive" } %>
        </div>

        <div class="specButton" data-controller="custom-form" data-action="click->custom-form#submit">
          Login
          <%= form.submit "Submit", hidden: true, data: { "custom-form-target": "submit" } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/setup.html.erb
<div data-controller="race-selector" data-race-selector-opts-value='<%= User.races %>' data-race-selector-images-value='<%= race_images %>' data-race-selector-current-value='<%= Current.user.race %>' class="race-selector">
<%= form_with model: Current.user, method: :put, class: "center" do |form| %>
  <h3>Name</h3>
  <%= form.text_field :name, disabled: true %>
  <h3>Race</h3>
    <%= render partial: "shared/race_selector" %>
    <%= form.hidden_field :race, value: Current.user.race, data: { "race-selector-target": "hiddenField" } %>
  <%= form.submit %>
<% end %>
</div>

app/views/worlds/index.html.erb
<div class="" data-controller="world">
  <%= turbo_frame_tag "action" %>

  <div class="navigation">
    <%= render(NavigationButton.new(link: "/shop", image: "GUI/icon_castle.png", text: "SHOP")) %>
    <%= render(NavigationButton.new(link: "/chat", image: "GUI/icon_book.png", text: "CHAT")) %>
    <%= render(NavigationButton.new(link: "/fights", image: "GUI/icon_sword.png", text: "FIGHT")) %>
  </div>
</div>